name: Build & Showcase Elysium OS ISO

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-showcase:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ISO and take screenshot in Arch Linux container
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:base-devel
          options: --privileged -v ${{ github.workspace }}:/workspace
          run: |
            set -e
            pacman -Sy --noconfirm archiso git python python-pip imagemagick xorg-server-xvfb qemu-base base-devel fastfetch rofi picom tmux zsh fzf ripgrep btop feh xclip
            cd /workspace
            bash build_and_test_elysium.sh

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: elysium-os-iso
          path: out/*.iso

      - name: Upload Showcase Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: elysium-os-showcase-screenshot
          path: screenshots/elysium-showcase.png