jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ISO in Arch Linux Docker
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:base-devel
          options: -v ${{ github.workspace }}:/workspace
          run: |
            set -e
            pacman -Sy --noconfirm archiso git python python-pip imagemagick xorg-server-xvfb qemu-base base-devel neofetch rofi picom tmux zsh fzf ripgrep btop feh xclip
            cd /workspace
            bash build_and_test_elysium.sh

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: elysium-os-iso
          path: out/*.iso

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: elysium-os-screenshots
          path: screenshots/*.png