name: Build & Test Elysium OS ISO

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y arch-install-scripts qemu-utils qemu-system-x86 imagemagick xvfb x11-apps git python3 python3-pip

      - name: Prepare pacman & archiso
        run: |
          sudo bash -c "echo '[multilib]' >> /etc/pacman.conf"
          sudo bash -c "echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf"
          sudo bash -c "echo 'Server = https://mirror.rackspace.com/archlinux/\$repo/os/\$arch' >> /etc/pacman.d/mirrorlist"
          sudo pacman -Syy --noconfirm
          sudo pacman -S --noconfirm archiso

      - name: Build and test Elysium OS (ISO + screenshot)
        run: bash build_and_test_elysium.sh

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: elysium-os-iso
          path: out/*.iso

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: elysium-os-screenshots
          path: screenshots/*.png